version: '3'

services:
  jobdash.server:
    image: shortpoet/jobdash-server
    build:
      context: .
      dockerfile: docker/Dockerfile-server
    tty: true
    stdin_open: true
    working_dir: /app/server
    command: yarn run start:dev
    environment:
      - DOCKER=1
    depends_on:
      - mongo
    ports:
      - 3000:3000
    volumes:
      - .:/app

  jobdash.client:
    image: shortpoet/jobdash-client
    build:
      context: .
      dockerfile: docker/Dockerfile-client
    tty: true
    working_dir: /app/dashboard
    command: yarn dev
    ports:
      - 8080:8080
    volumes:
      - .:/app

  mongo:
    image: mongo
    restart: always
    volumes:
      - tmp.mongodata:/data/db
    container_name: mongo
    # NOTE: Use these variables to enable authentication for mongo and mongo-express (duplicate below)
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
      
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 8081:8081

volumes:
  tmp.mongodata:
  