version: '3'

# TODO
#   add env file
#   add ternary for debug env that prints yarn warnings
# #TODO

services:
  jobdash.server:
    image: shortpoet/jobdash-server
    build:
      context: .
      dockerfile: docker/Dockerfile-server
    tty: true
    stdin_open: true
    working_dir: /opt/node_app/app/server
    command: yarn run start:dev
    environment:
      - DOCKER=1
    depends_on:
      - mongo
    ports:
      - 3000:3000
    volumes:
      - .:/opt/node_app/app

  jobdash.client:
    image: shortpoet/jobdash-client
    build:
      context: .
      dockerfile: docker/Dockerfile-client
    tty: true
    working_dir: /opt/node_app/app/dashboard
    command: yarn docker
    ports:
      - 8080:8080
    volumes:
      - .:/opt/node_app/app

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    command: [--auth]
    volumes:
      - ./server/seed/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: admin # database name

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: admin # database name
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      # ME_CONFIG_MONGODB_DATABASE: job-db
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - 8081:8081
