FROM node:12

# Install node_modules in container into directory above app code, which node will find.
# See: https://www.docker.com/blog/keep-nodejs-rockin-in-docker/
WORKDIR /opt/node_app

COPY dashboard/package.json dashboard/*yarn* ./

RUN yarn install

ENV PATH /opt/node_app/node_modules/.bin:$PATH

WORKDIR /opt/node_app/app
